#!/bin/bash

if [ $# -eq 0 ]; then
  memo e
  exit
fi

if [ "x$1" = "x-usage" ]; then
  echo "memo ge PATTERN"
  echo "then you can grep, select and edit it."
  exit
fi

memo g "$@" | sed 's/^.*\/\(.*\.md\)/\1/' | peco --on-cancel=error | awk 'BEGIN{FS=":"};{print $1}' | xargs -r memo e 
