#!/bin/bash

if [ "x$1" = "x-usage" ]; then
  echo "memo ge PATTERN"
  echo "then you can grep, select and edit it."
  exit
fi

memo e $(basename $(memo g "$@" | peco | awk 'BEGIN{FS=":"};{print $1}'))
