#!/bin/bash

if [ "x$1" = "x-usage" ]; then
  echo "memo ge PATTERN"
  echo "then you can grep, select and edit it."
  exit
fi

if [ $# -eq 0 ]; then
  memo e
  exit 0
fi

memo e $(memo g "$@" | sed 's/^.*\/\(.*\.md\)/\1/' | peco | awk 'BEGIN{FS=":"};{print $1}')
